# Generated by Django 5.2.12 on 2026-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration_minutes",
            field=models.IntegerField(default=120),
        ),
    ]
