# Generated by Django 5.2.12 on 2026-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration_minutes",
            field=models.IntegerField(),
        ),
    ]
