# Generated by Django 5.2.12 on 2026-03-17 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_duration_minutes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Filme", "verbose_name_plural": "Filmes"},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Sessão",
                "verbose_name_plural": "Sessões",
            },
        ),
    ]
